pub mod vs {
    vulkano_shaders::shader! {
        ty: "vertex",
        path: "src/shaders/shader.vert",
    }

    // TODO: Remove this, should be generated by vulkano-shaders!
    use bytemuck::{Pod, Zeroable};
    unsafe impl Zeroable for ty::VertPC {}
    unsafe impl Pod for ty::VertPC {}
}

pub mod fs {
    vulkano_shaders::shader! {
        ty: "fragment",
        path: "src/shaders/shader.frag",
    }
}
